export const CHANGE_LOCALE = 'CHANGE_LOCALE';
export const LOAD_WEB3 = 'LOAD_WEB3';
export const LOAD_BLOCKCHAIN = 'LOAD_BLOCKCHAIN';
export const LOAD_SMART_CONTRACTS = 'LOAD_SMART_CONTRACTS';
export const LOAD_CARDS = 'LOAD_CARDS';
export const LOADED_CARDS = 'LOADED_CARDS';
export const LOAD_BLOCKCHAIN_ERROR = 'LOAD_BLOCKCHAIN_ERROR';
